name: Run hadolint with GitHub Actions
on: [push]
jobs:
  Run-Hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run hadolint
        uses: docker://hadolint/hadolint:2.8.0-alpine
        with:
          entrypoint: /bin/hadolint
          args: flask_code/Dockerfile
