name: Run hadolint with GitHub Actions
on: [push]
jobs:
  Stat-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "flask_code/Dockerfile"
  Run-Hadolint:
    needs: Stat-Dockerfile
    runs-on: ubuntu-latest
    container: hadolint/hadolint:2.8.0-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run hadolint
        run: /bin/hadolint flask_code/Dockerfile
